addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.8.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.20.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.7")
addSbtPlugin("org.typelevel" %% "sbt-feral-lambda" % "0.1.0-M1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")